# Generated by Django 5.1.6 on 2025-02-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('bloodGroup', models.CharField(max_length=5)),
                ('rollNumber', models.CharField(max_length=15)),
                ('currMeds', models.TextField()),
            ],
        ),
    ]
